services:
  db:
      image: postgres:latest
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        DATABASE_URL=postgresql://db:19790109@db:5432/blogging
      networks:
        - mynetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 19790109
      DATABASE_HOST: db  # Nome do serviço do banco de dados
      DATABASE_NAME: blogging
      DATABASE_PORT: 5432
    ports:
       - "3000:3000"
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "30s", "./start.sh"]
    depends_on:
      - db
    networks:
      - mynetwork  
 
networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:    