services:
  postgres:
      image: postgres:latest
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 19790109
        POSTGRES_DB: blogging       
      networks:
        - mynetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 19790109
      DATABASE_HOST: blogging-postgres-1  # Nome do serviço do banco de dados
      DATABASE_NAME: blogging
      DATABASE_PORT: 5432
    ports:
       - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork  
 
networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:    