name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build e push da imagem Docker usando Buildx
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --platform linux/amd64 \
            -t rrsnaza/blogging:latest \
            --push .